name: build web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup emscripten
      run: |
          pwd
          ls -al
          sudo apt-get install -y git python3 cmake
          git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && git pull && ./emsdk install latest && ./emsdk activate latest && source ./emsdk_env.sh && cd ..
    
    - name: compile
      run: |
        source ./emsdk/emsdk_env.sh && emcc ./macos/src/*.cpp -I include -O2 -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s 'SDL2_IMAGE_FORMATS=["png", "jpg"]' -s USE_SDL_TTF=2 -s USE_SDL_MIXER=2 -s USE_SDL_GFX=2 --preload-file ./macos/data -o index.html
        
    - name: copy files to folder
      run: |
          mkdir emscripten && cp ./index.data ./emscripten && cp ./index.html ./emscripten  && cp ./index.js ./emscripten  && cp ./index.wasm ./emscripten
    
    - name: Upload web wasm
      uses: actions/upload-artifact@v2
      with:
            name: emscripten
            path: ./emscripten
            
      
