name: build windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019
    defaults:
      run:
        working-directory: ./windows

    steps:
    - uses: actions/checkout@v3
    
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw64/mingw-w64-x86_64-SDL2
          mingw64/mingw-w64-x86_64-SDL2_mixer
          mingw64/mingw-w64-x86_64-SDL2_image
          mingw64/mingw-w64-x86_64-SDL2_ttf
          mingw64/mingw-w64-x86_64-SDL2_gfx
     
    - name: copy resources
      run: |
        copy ./data/* ./build
    
    - name: compile
      run: |
       g++ -c src/*.cpp -std=c++17 -O3 -Wall -m64 -I D:/a/_temp/msys64/mingw64/include && g++ *.o -o bin/release/main -s -L D:/a/_temp/msys64/mingw64/lib -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer
    
    - name: compress
      run: |
        mkdir release
        tar -cvf ./release/artifacts.tar ./build
        
    - name: Upload win exe
      uses: actions/upload-artifact@v3
      with:
          name: artifacts
          path: /windows/bin/
    


