name: build windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./windows
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v3
    
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw64/mingw-w64-x86_64-SDL2
          mingw64/mingw-w64-x86_64-SDL2_mixer
          mingw64/mingw-w64-x86_64-SDL2_image
          mingw64/mingw-w64-x86_64-SDL2_ttf
          mingw64/mingw-w64-x86_64-SDL2_gfx
          mingw-w64-x86_64-toolchain
     
    - name: copy resources
      run: |
        cp -vr ./data/* ./build/data
        mkdir -p bin/release
    
    - name: compile
      run: |
       g++ -Wall -m64 -std=c++17 -O3 src/*.cpp -o build/game -I D:/a/_temp/msys64/mingw64/include -L D:/a/_temp/msys64/mingw64/lib -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -lSDL2_gfx
    
    - name: compress
      run: |
        tar -cvf ./bin/release/artifacts.tar ./build
        
    - name: Upload win exe
      uses: actions/upload-artifact@v3
      with:
          name: artifacts
          path: ./bin/release
    


