name: build windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019
    defaults:
      run:
        working-directory: ./windows

    steps:
    - uses: actions/checkout@v3
    
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw64/mingw-w64-x86_64-SDL2
          mingw64/mingw-w64-x86_64-SDL2_mixer
          mingw64/mingw-w64-x86_64-SDL2_image
          mingw64/mingw-w64-x86_64-SDL2_ttf
          mingw64/mingw-w64-x86_64-SDL2_net
     
    - name: copy resources
      run: |
        cp -vr ./data ./build
    
    - name: compile
      run: |
        g++ -Wall -std=c++17 -O3 src/*.cpp -o ./build/game `sdl2-config --cflags --libs`
    
    - name: compress
      run: |
        mkdir release
        tar -cvf ./release/artifacts.tar ./build
        
    - name: Upload win exe
      uses: actions/upload-artifact@v3
      with:
          name: artifacts
          path: /windows/bin/
    


